name: testing

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: actions/setup-node@v1
      - run: make setup
      - run: make test
      - run: make lint